server.port=7600

#logInUrl=https://bankreturnstest.centralbank.go.ke/bsaapi/api/Login/v2
logInUrl=https://bankreturns.centralbank.go.ke/bsaapi/api/Login/v2
user=E0000054202601
password=Victoriabank@20



#submissionUrl=https://bankreturnstest.centralbank.go.ke/bsaapi/api/Submissionv2/v2?returnKey=%s&version=%s
submissionUrl=https://bankreturns.centralbank.go.ke/bsaapi/api/Submissionv2/v2?returnKey=%s&version=%s
#statusUrl=https://bankreturnstest.centralbank.go.ke/bsaapi/api/Status/v2?fileName=%s&version=%s
statusUrl=https://bankreturns.centralbank.go.ke/bsaapi/api/Status/v2?fileName=%s&version=%s

returnKey_Sales=CBK/FX52API_28202001
returnKey_Holdings=CBK/FX54API_18400001
returnKey_Payments=CBK/FX52API_18200001
returnKey_Purchases=CBK/FX51API_28102001
returnKey_Receipts=CBK/FX51API_18100001
returnKey_Derivatives=CBK/FX90API_19000001
version=2
InstCode=0000054

enc.key= VcbKey0123456789
enc.initVector= VcbInitVector012

##Oracle uat Database Credentials
#db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
#db.ip= CGxr1GoPVFJikXm0OGs8mQ==
#db.port= ZWUMLtiLJf0orh1JZA7NGg==
#db.database= 2HLR3+xRrSXFxOxkSS4fEA==
#db.username= +J9A3QabNG8ckUqPt0oP/Q==
#db.password= MYQJVb6IXoqWd5MCi1NyBg==



##Oracle  Database Credentials
db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
db.ip= YiX4CjbsEdbqRCZ2VxwOLg==
db.port= ZWUMLtiLJf0orh1JZA7NGg==
db.database= Ez5WAN6W8WqweKrzm5Za7Q==
db.username= Qay8zWBA4/T7AKo4pNFEdQ==
db.password= Qay8zWBA4/T7AKo4pNFEdQ==



sqlFetchHoldings=SELECT account_ref,account_name,account_type,currency,amount,sector_code,cross_rate,FROM custom.forex;
sqlFetchPayments=SELECT transrefcode,customername,currency,amount,timestamp,spotexchangerate,crossrate,usdequivalent,sectorcode FROM custom.FOREX_PAYMENTS WHERE forexType = 'P' AND posted_flag = 'N'
sqlFetchPurchases=SELECT transrefcode,customername,currency,amount,timestamp,spotexchangerate,crossrate,usdequivalent,INTERBANK_CODES,sectorcode FROM custom.forex_purchases WHERE forexType = 'P' AND posted_flag = 'N'
sqlFetchSales=SELECT transrefcode,customername,currency,amount,timestamp,spotexchangerate,crossrate,usdequivalent,INTERBANK_CODES,sectorcode FROM custom.forex_sales WHERE forexType = 'S' AND posted_flag = 'N'
sqlFetchReceipts=SELECT transrefcode,customername,currency,amount,timestamp,spotexchangerate,crossrate,usdequivalent,sectorcode FROM custom.forex WHERE forexType = 'R' AND posted_flag = 'N'
sqlFetchDerivatives=SELECT trans_ref_code,account_name AS customer_name,contract_id,currency,notional_principal_amount,timestamp,position,contract_start_date,contract_end_date,valuation_date,settlement_date,price_rate,exchange_rate,cross_rate,usd_equivalent,derivative_code,derivative_type,sector_code FROM custom.forex
##Oracle EMTECH Database Credentials
#db.class= mmR/m2BcaZWL+kTu86/9mlWmb9E27fsv3QnWKjkWIx4=
#db.ip= 9Kq89HX1UjiiHMJLK//emA==
#db.port= ZWUMLtiLJf0orh1JZA7NGg==
#db.database= Y60tpFpra9AsNi/lpikibg==
#db.username= +J9A3QabNG8ckUqPt0oP/Q==
#db.password= MYQJVb6IXoqWd5MCi1NyBg==